# Calculations for Cartpole Eigenvalues

In [13]:
import numpy as np

# original values
a = 0.98
b = 21.56
sqrtb = np.sqrt(b)
tau = 0.02
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = 2*(e_a_tau-1)/a
A_22 = 2*e_a_tau
A_33 =e_negb_tau*(e_2sqrtb_tau + 1)
A_34 = e_negb_tau*(e_2sqrtb_tau-1)/sqrtb
A_43 = sqrtb*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = e_negb_tau*(e_2sqrtb_tau + 1)
A = 0.5*np.array([[2, A_12, 0, 0],
         [0, A_22, 0, 0],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])
print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")



======= A =======
[[1.         0.02019729 0.         0.        ]
 [0.         1.01979334 0.         0.        ]
 [0.         0.         1.0043151  0.02002876]
 [0.         0.         0.43182005 1.0043151 ]]
[1.09731413 0.91131607 1.         1.01979334]
======= A - BK =======


In [14]:
# original values
a = 1.96
b = 47.04
sqrtb = np.sqrt(b)
tau = 0.02
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = 2*(e_a_tau-1)/a
A_22 = 2*e_a_tau
A_33 =e_negb_tau*(e_2sqrtb_tau + 1)
A_34 = e_negb_tau*(e_2sqrtb_tau-1)/sqrtb
A_43 = sqrtb*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = e_negb_tau*(e_2sqrtb_tau + 1)
A = 0.5*np.array([[2, A_12, 0, 0],
         [0, A_22, 0, 0],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])
print(A)
print(np.linalg.eigvals(A))

[[1.         0.02039717 0.         0.        ]
 [0.         1.03997846 0.         0.        ]
 [0.         0.         1.00942276 0.02006278]
 [0.         0.         0.94375313 1.00942276]]
[1.14702476 0.87182076 1.         1.03997846]
