# Calculations for Cartpole Eigenvalues

In [19]:
import numpy as np
from scipy import signal
import scipy.integrate as integrate

# original values
m_c = 1
m_p = 0.1
l = 0.5
g = 9.8
a = g*m_p/m_c #0.98
b = g*(m_c+m_p)/(l*m_c) #21.56
sqrtb = np.sqrt(b)
tau = 0.02
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = 2*(e_a_tau-1)/a
A_22 = 2*e_a_tau
A_33 =e_negb_tau*(e_2sqrtb_tau + 1)
A_34 = e_negb_tau*(e_2sqrtb_tau-1)/sqrtb
A_43 = sqrtb*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = e_negb_tau*(e_2sqrtb_tau + 1)
A = 0.5*np.array([[2, A_12, 0, 0],
         [0, A_22, 0, 0],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])
print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")
# B = np.array([[0],
#               [1/m_c],
#               [0],
#               [-1/(l*m_c)]])


B_2_f = lambda x: (1/m_c)*np.exp(a*x)
B_4_f = lambda x: (-1/(2*l*m_c))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)+1)
B_2 = integrate.quad(B_2_f, 0, tau)[0]
B_4 = integrate.quad(B_4_f, 0, tau)[0]
B = np.array([[0],
              [B_2],
              [0],
              [B_4]])

requested_poles = np.array([0.95, 0.94, 0.96, 0.956])
# requested_poles = np.array([0.8, 0.82, 0.84, 0.86])

out = signal.place_poles(A, B, requested_poles)
print(out.gain_matrix)
print(out.computed_poles)
print(out.requested_poles)

======= A =======
[[1.         0.02019729 0.         0.        ]
 [0.         1.01979334 0.         0.        ]
 [0.         0.         1.0043151  0.02002876]
 [0.         0.         0.43182005 1.0043151 ]]
[1.09731413 0.91131607 1.         1.01979334]
======= A - BK =======
[[ -1.49977814  -4.78848863 -37.30568393  -7.96699431]]
[0.94  0.95  0.956 0.96 ]
[0.94  0.95  0.956 0.96 ]


In [20]:
# original values
m_c = 1
m_p = 0.2
l = 0.25
g = 9.8
a = g*m_p/m_c
b = g*(m_c+m_p)/(l*m_c) 
sqrtb = np.sqrt(b)
tau = 0.02
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = 2*(e_a_tau-1)/a
A_22 = 2*e_a_tau
A_33 =e_negb_tau*(e_2sqrtb_tau + 1)
A_34 = e_negb_tau*(e_2sqrtb_tau-1)/sqrtb
A_43 = sqrtb*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = e_negb_tau*(e_2sqrtb_tau + 1)
A = 0.5*np.array([[2, A_12, 0, 0],
         [0, A_22, 0, 0],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])

print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")
# continuous time B
# B = np.array([[0],
#               [1/m_c],
#               [0],
#               [-1/(l*m_c)]])

B_2_f = lambda x: (1/m_c)*np.exp(a*x)
B_4_f = lambda x: (-1/(2*l*m_c))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)+1)
B_2 = integrate.quad(B_2_f, 0, tau)[0]
B_4 = integrate.quad(B_4_f, 0, tau)[0]
B = np.array([[0],
              [B_2],
              [0],
              [B_4]])


requested_poles = np.array([0.95, 0.94, 0.96, 0.956])
# requested_poles = np.array([0.8, 0.82, 0.84, 0.86])

out = signal.place_poles(A, B, requested_poles)
print(out.gain_matrix)
print(out.computed_poles)
print(out.requested_poles)

======= A =======
[[1.         0.02039717 0.         0.        ]
 [0.         1.03997846 0.         0.        ]
 [0.         0.         1.00942276 0.02006278]
 [0.         0.         0.94375313 1.00942276]]
[1.14702476 0.87182076 1.         1.03997846]
======= A - BK =======
[[ -0.67341968  -3.77266595 -29.3239967   -4.10929736]]
[0.94  0.95  0.956 0.96 ]
[0.94  0.95  0.956 0.96 ]
