# Calculations for Cartpole Eigenvalues

In [9]:
import numpy as np
from scipy import signal
import scipy.integrate as integrate

# original values
m_c = 1
m_p = 0.1
l = 0.5
g = 9.8
a = g*m_p/m_c #0.98
b = g*(m_c+m_p)/(l*m_c) #21.56
sqrtb = np.sqrt(b)
tau = 0.1
# e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = tau
A_13 = (a/(2*b))*e_negb_tau*(e_sqrtb_tau-1)**2
A_14 = (a/(2*b**(3/2)))*e_negb_tau*(-1*sqrtb*tau*e_sqrtb_tau+e_2sqrtb_tau-1)
A_22 = (a/(2*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_23 = (a/(2*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_24 = (a/(2*b))*e_negb_tau*(e_sqrtb_tau-1)**2
A_33 = (1/(2))*e_negb_tau*(e_2sqrtb_tau+1)
A_34 = (1/(a*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_43 = (sqrtb/(2))*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = (1/2)*e_negb_tau*(e_2sqrtb_tau+1)
A = np.array([[1, A_12, A_13, A_14],
         [0, 1, A_23, A_24],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])
print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")
# B = np.array([[0],
#               [1/m_c],
#               [0],
#               [-1/(l*m_c)]])


B_1_f = lambda x: (x/m_c)-(a/(l*m_c*2*b**(3/2)))*np.exp(-np.sqrt(b)*x)*(-2*sqrtb*tau*np.exp(np.sqrt(b)*x)+np.exp(2*np.sqrt(b)*x)-1)
B_2_f = lambda x: (1/m_c)-(a/(l*m_c*2*b))*np.exp(-np.sqrt(b)*x)*(np.exp(np.sqrt(b)*x)-1)**2
B_3_f = lambda x: -(1/(l*m_c*2*sqrtb))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)-1)
B_4_f = lambda x: -(1/(l*m_c*2))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)+1)
B_1 = integrate.quad(B_1_f, 0, tau)[0]
B_2 = integrate.quad(B_2_f, 0, tau)[0]
B_3 = integrate.quad(B_3_f, 0, tau)[0]
B_4 = integrate.quad(B_4_f, 0, tau)[0]
B = np.array([[B_1],
              [B_2],
              [B_3],
              [B_4]])
print(B)
requested_poles = np.array([0.9, 0.91, 0.89, 0.75])

# requested_poles = np.array([0.8, 0.82, 0.84, 0.86])

out = signal.place_poles(A, B, requested_poles)
print(out.gain_matrix)
print(out.computed_poles)
print(out.requested_poles)

======= A =======
[[1.         0.1        0.00498867 0.00243783]
 [0.         1.         0.10155962 0.00498867]
 [0.         0.         1.10975078 0.21149443]
 [0.         0.         2.23431172 1.10975078]]
[1.         1.         1.79716948 0.42233208]
======= A - BK =======
[[ 0.00544632]
 [ 0.09966979]
 [-0.01018096]
 [-0.20726454]]
[[ -0.04926718  -0.16348671 -13.15347572  -3.14645973]]
[0.75 0.89 0.9  0.91]
[0.75 0.89 0.9  0.91]


In [7]:
# fast values
m_c = 1
m_p = 0.5
l = 0.25
g = 9.8
a = g*m_p/m_c
b = g*(m_c+m_p)/(l*m_c) 
sqrtb = np.sqrt(b)
tau = 0.1
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)
A_12 = tau
A_13 = (a/(2*b))*e_negb_tau*(e_sqrtb_tau-1)**2
A_14 = (a/(2*b**(3/2)))*e_negb_tau*(-1*sqrtb*tau*e_sqrtb_tau+e_2sqrtb_tau-1)
A_22 = (a/(2*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_23 = (a/(2*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_24 = (a/(2*b))*e_negb_tau*(e_sqrtb_tau-1)**2
A_33 = (1/(2))*e_negb_tau*(e_2sqrtb_tau+1)
A_34 = (1/(a*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_43 = (sqrtb/(2))*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = (1/2)*e_negb_tau*(e_2sqrtb_tau+1)
A = np.array([[1, A_12, A_13, A_14],
         [0, 1, A_23, A_24],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])
print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")
# B = np.array([[0],
#               [1/m_c],
#               [0],
#               [-1/(l*m_c)]])


B_1_f = lambda x: (x/m_c)-(a/(l*m_c*2*b**(3/2)))*np.exp(-np.sqrt(b)*x)*(-2*sqrtb*tau*np.exp(np.sqrt(b)*x)+np.exp(2*np.sqrt(b)*x)-1)
B_2_f = lambda x: (1/m_c)-(a/(l*m_c*2*b))*np.exp(-np.sqrt(b)*x)*(np.exp(np.sqrt(b)*x)-1)**2
B_3_f = lambda x: -(1/(l*m_c*2*sqrtb))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)-1)
B_4_f = lambda x: -(1/(l*m_c*2))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)+1)
B_1 = integrate.quad(B_1_f, 0, tau)[0]
B_2 = integrate.quad(B_2_f, 0, tau)[0]
B_3 = integrate.quad(B_3_f, 0, tau)[0]
B_4 = integrate.quad(B_4_f, 0, tau)[0]
B = np.array([[B_1],
              [B_2],
              [B_3],
              [B_4]])
print(B)
requested_poles = np.array([0.9, 0.91, 0.89, 0.75])
# requested_poles = np.array([0.8, 0.82, 0.84, 0.86])

out = signal.place_poles(A, B, requested_poles)
print(out.gain_matrix)
print(out.computed_poles)
print(out.requested_poles)

======= A =======
[[1.00000000e+00 1.00000000e-01 2.57242785e-02 5.00768223e-03]
 [0.00000000e+00 1.00000000e+00 5.39451715e-01 2.57242785e-02]
 [0.00000000e+00 0.00000000e+00 1.30869134e+00 4.49355864e-02]
 [0.00000000e+00 0.00000000e+00 6.47342058e+00 1.30869134e+00]]
[1.         1.         1.84803071 0.76935198]
======= A - BK =======
[[ 0.00658338]
 [ 0.09663594]
 [-0.02099941]
 [-0.44036875]]
[[ -0.09490195  -0.28869755 -20.8180347   -1.72296412]]
[0.75 0.89 0.9  0.91]
[0.75 0.89 0.9  0.91]


In [8]:
# slow values
m_c = 2
m_p = 0.1
l = 1.0
g = 9.8
a = g*m_p/m_c
b = g*(m_c+m_p)/(l*m_c) 
sqrtb = np.sqrt(b)
tau = 0.1
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = tau
A_13 = (a/(2*b))*e_negb_tau*(e_sqrtb_tau-1)**2
A_14 = (a/(2*b**(3/2)))*e_negb_tau*(-1*sqrtb*tau*e_sqrtb_tau+e_2sqrtb_tau-1)
A_22 = (a/(2*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_23 = (a/(2*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_24 = (a/(2*b))*e_negb_tau*(e_sqrtb_tau-1)**2
A_33 = (1/(2))*e_negb_tau*(e_2sqrtb_tau+1)
A_34 = (1/(a*sqrtb))*e_negb_tau*(e_2sqrtb_tau-1)
A_43 = (sqrtb/(2))*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = (1/2)*e_negb_tau*(e_2sqrtb_tau+1)
A = np.array([[1, A_12, A_13, A_14],
         [0, 1, A_23, A_24],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])
print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")
# B = np.array([[0],
#               [1/m_c],
#               [0],
#               [-1/(l*m_c)]])


B_1_f = lambda x: (x/m_c)-(a/(l*m_c*2*b**(3/2)))*np.exp(-np.sqrt(b)*x)*(-2*sqrtb*tau*np.exp(np.sqrt(b)*x)+np.exp(2*np.sqrt(b)*x)-1)
B_2_f = lambda x: (1/m_c)-(a/(l*m_c*2*b))*np.exp(-np.sqrt(b)*x)*(np.exp(np.sqrt(b)*x)-1)**2
B_3_f = lambda x: -(1/(l*m_c*2*sqrtb))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)-1)
B_4_f = lambda x: -(1/(l*m_c*2))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)+1)
B_1 = integrate.quad(B_1_f, 0, tau)[0]
B_2 = integrate.quad(B_2_f, 0, tau)[0]
B_3 = integrate.quad(B_3_f, 0, tau)[0]
B_4 = integrate.quad(B_4_f, 0, tau)[0]
B = np.array([[B_1],
              [B_2],
              [B_3],
              [B_4]])
print(B)
requested_poles = np.array([0.9, 0.91, 0.89, 0.75])

# requested_poles = np.array([0.8, 0.82, 0.84, 0.86])

out = signal.place_poles(A, B, requested_poles)
print(out.gain_matrix)
print(out.computed_poles)
print(out.requested_poles)

======= A =======
[[1.         0.1        0.00247108 0.00246304]
 [0.         1.         0.04984468 0.00247108]
 [0.         0.         1.0518927  0.41519937]
 [0.         0.         1.04673837 1.0518927 ]]
[1.         1.         1.71113856 0.39264684]
======= A - BK =======
[[ 0.00261802]
 [ 0.04995896]
 [-0.00252151]
 [-0.05086192]]
[[ -0.10939722  -0.36581336 -25.50751584 -11.95452197]]
[0.75 0.89 0.9  0.91]
[0.75 0.89 0.9  0.91]
