# Calculations for Cartpole Eigenvalues

In [12]:
import numpy as np
from scipy import signal
import scipy.integrate as integrate

# original values
m_c = 1
m_p = 0.1
l = 0.5
g = 9.8
a = g*m_p/m_c #0.98
b = g*(m_c+m_p)/(l*m_c) #21.56
sqrtb = np.sqrt(b)
tau = 0.1
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = 2*(e_a_tau-1)/a
A_22 = 2*e_a_tau
A_33 =e_negb_tau*(e_2sqrtb_tau + 1)
A_34 = e_negb_tau*(e_2sqrtb_tau-1)/sqrtb
A_43 = sqrtb*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = e_negb_tau*(e_2sqrtb_tau + 1)
A = 0.5*np.array([[2, A_12, 0, 0],
         [0, A_22, 0, 0],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])
print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")
# B = np.array([[0],
#               [1/m_c],
#               [0],
#               [-1/(l*m_c)]])


B_2_f = lambda x: (1/m_c)*np.exp(a*x)
B_4_f = lambda x: (-1/(2*l*m_c))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)+1)
B_2 = integrate.quad(B_2_f, 0, tau)[0]
B_4 = integrate.quad(B_4_f, 0, tau)[0]
B = np.array([[0],
              [B_2],
              [0],
              [B_4]])
print(B)
requested_poles = np.array([0.55, 0.54, 0.56, 0.556])
# requested_poles = np.array([0.8, 0.82, 0.84, 0.86])

out = signal.place_poles(A, B, requested_poles)
print(out.gain_matrix)
print(out.computed_poles)
print(out.requested_poles)

======= A =======
[[1.         0.10506407 0.         0.        ]
 [0.         1.10296279 0.         0.        ]
 [0.         0.         1.10975078 0.10363227]
 [0.         0.         2.23431172 1.10975078]]
[1.59094387 0.62855769 1.         1.10296279]
======= A - BK =======
[[ 0.        ]
 [ 0.10506407]
 [ 0.        ]
 [-0.20726454]]
[[-16.69013967 -19.88541266 -94.22811357 -20.29149176]]
[0.54  0.55  0.556 0.56 ]
[0.54  0.55  0.556 0.56 ]


In [14]:
# fast values
m_c = 1
m_p = 0.5
l = 0.25
g = 9.8
a = g*m_p/m_c
b = g*(m_c+m_p)/(l*m_c) 
sqrtb = np.sqrt(b)
tau = 0.1
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = 2*(e_a_tau-1)/a
A_22 = 2*e_a_tau
A_33 =e_negb_tau*(e_2sqrtb_tau + 1)
A_34 = e_negb_tau*(e_2sqrtb_tau-1)/sqrtb
A_43 = sqrtb*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = e_negb_tau*(e_2sqrtb_tau + 1)
A = 0.5*np.array([[2, A_12, 0, 0],
         [0, A_22, 0, 0],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])

print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")
# continuous time B
# B = np.array([[0],
#               [1/m_c],
#               [0],
#               [-1/(l*m_c)]])

B_2_f = lambda x: (1/m_c)*np.exp(a*x)
B_4_f = lambda x: (-1/(2*l*m_c))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)+1)
B_2 = integrate.quad(B_2_f, 0, tau)[0]
B_4 = integrate.quad(B_4_f, 0, tau)[0]
B = np.array([[0],
              [B_2],
              [0],
              [B_4]])

print(B)
requested_poles = np.array([0, 0.54, 0.56, 0.556])
# requested_poles = np.array([0.8, 0.82, 0.84, 0.86])

out = signal.place_poles(A, B, requested_poles)
print(out.gain_matrix)
print(out.computed_poles)
print(out.requested_poles)

======= A =======
[[1.         0.12904413 0.         0.        ]
 [0.         1.63231622 0.         0.        ]
 [0.         0.         1.30869134 0.11009219]
 [0.         0.         6.47342058 1.30869134]]
[2.15289098 0.4644917  1.         1.63231622]
======= A - BK =======
[[ 0.        ]
 [ 0.12904413]
 [ 0.        ]
 [-0.44036875]]
[[  -8.74102877  -39.70026499 -151.77476708  -19.79428599]]
[-1.50213175e-13  5.40000000e-01  5.56000000e-01  5.60000000e-01]
[0.    0.54  0.556 0.56 ]


In [15]:
# slow values
m_c = 2
m_p = 0.1
l = 1.0
g = 9.8
a = g*m_p/m_c
b = g*(m_c+m_p)/(l*m_c) 
sqrtb = np.sqrt(b)
tau = 0.1
e_a_tau = np.exp(a*tau)
e_sqrtb_tau = np.exp(sqrtb*tau)
e_2sqrtb_tau = np.exp(2*sqrtb*tau)
e_negb_tau = np.exp(-sqrtb*tau)

A_12 = 2*(e_a_tau-1)/a
A_22 = 2*e_a_tau
A_33 =e_negb_tau*(e_2sqrtb_tau + 1)
A_34 = e_negb_tau*(e_2sqrtb_tau-1)/sqrtb
A_43 = sqrtb*e_negb_tau*(e_2sqrtb_tau-1)
A_44 = e_negb_tau*(e_2sqrtb_tau + 1)
A = 0.5*np.array([[2, A_12, 0, 0],
         [0, A_22, 0, 0],
         [0, 0, A_33, A_34],
         [0, 0, A_43, A_44]])

print("======= A =======")
print(A)
print(np.linalg.eigvals(A))

# Now, we need to compute the B matrix for A-BK
print("======= A - BK =======")
# continuous time B
# B = np.array([[0],
#               [1/m_c],
#               [0],
#               [-1/(l*m_c)]])

B_2_f = lambda x: (1/m_c)*np.exp(a*x)
B_4_f = lambda x: (-1/(2*l*m_c))*np.exp(-np.sqrt(b)*x)*(np.exp(2*np.sqrt(b)*x)+1)
B_2 = integrate.quad(B_2_f, 0, tau)[0]
B_4 = integrate.quad(B_4_f, 0, tau)[0]
B = np.array([[0],
              [B_2],
              [0],
              [B_4]])

print(B)
requested_poles = np.array([0, 0.54, 0.56, -0.556])
# requested_poles = np.array([0.8, 0.82, 0.84, 0.86])

out = signal.place_poles(A, B, requested_poles)
print(out.gain_matrix)
print(out.computed_poles)
print(out.requested_poles)

======= A =======
[[1.         0.10249051 0.         0.        ]
 [0.         1.05022035 0.         0.        ]
 [0.         0.         1.0518927  0.10172385]
 [0.         0.         1.04673837 1.0518927 ]]
[1.37820275 0.72558264 1.         1.05022035]
======= A - BK =======
[[ 0.        ]
 [ 0.05124526]
 [ 0.        ]
 [-0.05086192]]
[[ -577.75872378  -360.65603003 -1455.30718064  -434.35078994]]
[-5.560000e-01 -1.045838e-12  5.400000e-01  5.600000e-01]
[-0.556  0.     0.54   0.56 ]
